# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hạt Đậu Nè
email: dauh32866@gmail.com
description: > # this means to ignore newlines until "baseurl:" Hạt Đậu nè 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hatdaune.github.io" # the base hostname & protocol for your site
github_username: hatdaune

theme: minima

plugins:
  - jekyll-seo-tag